//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.Web;

	public partial class Frontend_Image
    {
        public int ImageID { get; set; }
		[Required(ErrorMessage = "The Title cannot be blank")]
		[Display(Name = "Title")]
		public string Image_title { get; set; }
		[Required(ErrorMessage = "The photo cannot be blank")]
		[Display(Name = "photo")]
		public string Image_Path { get; set; }
		public HttpPostedFileBase ImageFile { get; set; }
	}
}
