//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Marksheet
    {
        public int marksheetID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> FacultyID { get; set; }
		[Required(ErrorMessage = "The Student name cannot be blank")]
		[StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter a Student name between 3 and 50 characters in length")]
		[RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$", ErrorMessage = "Please enter a Student name beginning with a capital letter and made up of letters and spaces only")]
		[Display(Name = "First Name")]
		public string StudentFirstName { get; set; }
		[StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter a Student name between 3 and 50 characters in length")]
		[RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$", ErrorMessage = "Please enter a Student name beginning with a capital letter and made up of letters and spaces only")]
		[Display(Name = "Middle Name")]
		public string StudnetMiddleName { get; set; }
		[Required(ErrorMessage = "The Student name cannot be blank")]
		[StringLength(50, MinimumLength = 3, ErrorMessage = "Please enter a Student name between 3 and 50 characters in length")]
		[RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$", ErrorMessage = "Please enter a Student name beginning with a capital letter and made up of letters and spaces only")]
		[Display(Name = "Last Name")]
		public string StudentLastName { get; set; }
		public Nullable<int> Full_marks { get; set; }
        public Nullable<int> Pass_marks { get; set; }
        public Nullable<decimal> Marks_obtain { get; set; }
        public string Subject_name { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
