//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Notice
    {
        public int NoticeId { get; set; }
		[Required(ErrorMessage = "The Date cannot be blank")]
		[Display(Name = "Date ")]
		public Nullable<System.DateTime> Publish_Date { get; set; }
        public Nullable<int> DepartmentID { get; set; }
		[Required(ErrorMessage = "The Subject cannot be blank")]
		[Display(Name = "Subject ")]
		public string Subject { get; set; }
		[Required(ErrorMessage = "The Description cannot be blank")]
		[Display(Name = "Description ")]
		public string Description { get; set; }
    }
}
